In [21]:
import numpy as np
import pandas as pd
import sys
sys.path.append('../')
sys.path.insert(0,'/home/hungjinh/python_lib/CAMB/pycamb')
from scipy import interpolate

from power_spectra import *

In [22]:
data_dir = "/home/hungjinh/Research/cov_baryon_proj/code/cosmic_shear/Pk_ratio/"
scenario = "eagle"
# other possible baryonic scenario:
# "owls_AGN","owls_DBLIMFV1618","owls_NOSN","owls_NOSN_NOZCOOL","owls_NOZCOOL","owls_REF","owls_WDENS"
# "owls_WML1V848","owls_WML4","illustris","mb2","eagle","HzAGN"

Bins_z_HzAGN   = np.array([4.9285,4.249,3.7384,3.33445,3.00295,1.96615,1.02715,0.519195,0.22878,0.017865,0.0])
Bins_z_mb2     = np.array([3.5,3.25,2.8,2.45,2.1,2.0,1.8,1.7,1.6,1.4,1.2,1.1,1.0,0.8,0.7,0.6,0.4,0.35,0.2,0.0625,0.0])
Bins_z_ill1    = np.array([3.5,3.49,3.28,3.08,2.90,2.73,2.44,2.1,2.0,1.82,1.74,1.6,1.41,1.21,1.04,1.0,0.79,0.7,0.6,0.4,0.35,0.2,0.0])
Bins_z_eagle   = np.array([3.53,3.02,2.48,2.24,2.01,1.74,1.49,1.26,1.0,0.74,0.5,0.27,0.0])
Bins_z_OWLS    = np.array([3.5,3.25,3.0,2.75,2.25,2.00,1.75,1.50,1.25,1.00,0.75,0.50,0.375,0.25,0.125,0.0])
Bins_z_NOSN    = np.array([3.5,3.25,3.0,2.75,2.25,2.00,1.75,1.50,1.25,1.00,0.75,0.50,0.375,0.25,0.0])

zbin_logPkR = {"owls_AGN":Bins_z_OWLS,
               "owls_DBLIMFV1618":Bins_z_OWLS,
               "owls_NOSN":Bins_z_NOSN,
               "owls_NOSN_NOZCOOL":Bins_z_OWLS,
               "owls_NOZCOOL":Bins_z_OWLS,
               "owls_REF":Bins_z_OWLS,
               "owls_WDENS":Bins_z_OWLS,
               "owls_WML1V848":Bins_z_OWLS,
               "owls_WML4":Bins_z_OWLS,
               "illustris":Bins_z_ill1,
               "mb2":Bins_z_mb2,
               "eagle":Bins_z_eagle,
               "HzAGN":Bins_z_HzAGN
              }

In [35]:
class gen_PkRatio():
    def __init__(self,data_dir,zbin_logPkR,scenario,z,kh):
        self.data_dir    = data_dir
        self.zbin_logPkR = zbin_logPkR
        self.scenario = scenario
        self.infile_logPkRatio = self.data_dir + "logPkRatio_" + scenario + ".dat"
        #self.DF_logPkR         = self.read_logPkR_file()
        self.Bins_z            = self.zbin_logPkR[scenario]
        self.f_logPkRatio      = f_logPkRatio
    
    def read_logPkR_file(self):
        DF_logPkR = pd.read_csv(self.infile_logPkRatio,sep='\s+')
        return DF_logPkR
    
    def f_logPkRatio(self):
        Arr2D_logPkratio = self.read_logPkR_file()
        Bins_log_k_Mpc = np.array(Arr2D_logPkratio["logk"])
        del Arr2D_logPkratio["logk"]
        Arr2D_logPkratio = np.array(Arr2D_logPkratio)
        f_logPkRatio = interpolate.interp2d(self.Bins_z, Bins_log_k_Mpc, Arr2D_logPkratio, kind='linear')
        return f_logPkRatio


In [24]:
gen_PkRatio = gen_PkRatio(data_dir,zbin_logPkR,scenario)

In [ ]:
[0],[-3.301030]

In [25]:
f_logPkRatio=gen_PkRatio.f_logPkRatio()

In [33]:
f_logPkRatio([0,1.74],[-3.301030,-3.166488,-3.031946,-2.897403])

array([[ -4.11060678e-25,  -2.05530339e-25],
       [  1.66617966e-08,   3.47941751e-09],
       [  6.39414913e-09,   1.33526504e-09],
       [ -3.08031827e-08,  -6.43250760e-09]])

In [26]:
gen_PkRatio.DF_logPkR

logk          z353          z302          z248          z224  \
0   -3.301030  1.027652e-25  0.000000e+00  2.569129e-26 -2.569129e-26   
1   -3.166488 -4.125639e-09 -3.106569e-09 -8.820669e-10  5.649808e-10   
2   -3.031946 -1.583248e-09 -1.192171e-09 -3.385004e-10  2.168160e-10   
3   -2.897403  7.627174e-09  5.743193e-09  1.630699e-09 -1.044494e-09   
4   -2.762861  1.244916e-08  9.374106e-09  2.661646e-09 -1.704836e-09   
5   -2.628319 -2.602175e-08 -1.959414e-08 -5.563482e-09  3.563517e-09   
6   -2.493777  4.602685e-08  3.465780e-08  9.840598e-09 -6.303092e-09   
7   -2.359234  4.826198e-07  3.634084e-07  1.031847e-07 -6.609180e-08   
8   -2.224692  1.287223e-06  9.692673e-07  2.752099e-07 -1.762772e-07   
9   -2.090150  2.459836e-06  1.852234e-06  5.259161e-07 -3.368594e-07   
10  -1.955608  4.000459e-06  3.012310e-06  8.553033e-07 -5.478382e-07   
11  -1.821065  5.909093e-06  4.449494e-06  1.263371e-06 -8.092138e-07   
12  -1.686523  8.185736e-06  6.163786e-06  1.750121e-06 -1.120986e-06   
13  -1.551981  1.083039e-05  8.155186e-06  2.315551e-06 -1.483155e-06   
14  -1.417439  1.384305e-05  1.042369e-05  2.959662e-06 -1.895721e-06   
15  -1.282896  1.722373e-05  1.296931e-05  3.682455e-06 -2.358683e-06   
16  -1.148354  2.097241e-05  1.579204e-05  4.483928e-06 -2.872042e-06   
17  -1.013812  2.508911e-05  1.889187e-05  5.364082e-06 -3.435798e-06   
18  -0.879270  2.957381e-05  2.226881e-05  6.322918e-06 -4.049951e-06   
19  -0.744727  3.442652e-05  2.592286e-05  7.360434e-06 -4.714500e-06   
20  -0.728366  3.504175e-05  2.638612e-05  7.491970e-06 -4.798751e-06   
21  -0.432419 -6.226381e-05 -1.020831e-04 -1.654074e-04 -1.978388e-04   
22  -0.235846 -2.709286e-04 -3.786234e-04 -5.377065e-04 -6.258480e-04   
23  -0.095867 -5.887602e-04 -8.109707e-04 -1.114354e-03 -1.294652e-03   
24   0.009341 -1.036255e-03 -1.406607e-03 -1.928806e-03 -2.212331e-03   
25   0.094767 -1.653299e-03 -2.238649e-03 -3.022235e-03 -3.444769e-03   
26   0.166137 -2.395433e-03 -3.264096e-03 -4.440989e-03 -5.015608e-03   
27   0.226785 -3.296260e-03 -4.493482e-03 -6.062050e-03 -6.844041e-03   
28   0.280442 -4.293353e-03 -5.829299e-03 -7.799879e-03 -8.765841e-03   
29   0.328456 -5.445317e-03 -7.384281e-03 -9.845106e-03 -1.101352e-02   
..        ...           ...           ...           ...           ...   
279  2.848191  4.125991e-01  4.171456e-01  5.394118e-01  6.458591e-01   
280  2.859498  4.184048e-01  4.227614e-01  5.465555e-01  6.543900e-01   
281  2.870805  4.242462e-01  4.284100e-01  5.537412e-01  6.629718e-01   
282  2.882112  4.301233e-01  4.340915e-01  5.609690e-01  6.716044e-01   
283  2.893419  4.360360e-01  4.398058e-01  5.682387e-01  6.802879e-01   
284  2.904725  4.419843e-01  4.455531e-01  5.755505e-01  6.890222e-01   
285  2.916032  4.479683e-01  4.513331e-01  5.829042e-01  6.978073e-01   
286  2.927339  4.539880e-01  4.571461e-01  5.903000e-01  7.066433e-01   
287  2.938646  4.600433e-01  4.629919e-01  5.977378e-01  7.155301e-01   
288  2.949953  4.661342e-01  4.688706e-01  6.052176e-01  7.244677e-01   
289  2.961260  4.722608e-01  4.747822e-01  6.127394e-01  7.334562e-01   
290  2.972567  4.784230e-01  4.807266e-01  6.203032e-01  7.424956e-01   
291  2.983874  4.846209e-01  4.867039e-01  6.279090e-01  7.515857e-01   
292  2.995181  4.908545e-01  4.927140e-01  6.355569e-01  7.607267e-01   
293  3.006488  4.971237e-01  4.987571e-01  6.432467e-01  7.699186e-01   
294  3.017795  5.034285e-01  5.048330e-01  6.509785e-01  7.791613e-01   
295  3.029101  5.097690e-01  5.109417e-01  6.587524e-01  7.884548e-01   
296  3.040408  5.161452e-01  5.170834e-01  6.665683e-01  7.977992e-01   
297  3.051715  5.225570e-01  5.232579e-01  6.744261e-01  8.071944e-01   
298  3.063022  5.290044e-01  5.294652e-01  6.823260e-01  8.166405e-01   
299  3.074329  5.354875e-01  5.357055e-01  6.902679e-01  8.261374e-01   
300  3.085636  5.420063e-01  5.419785e-01  6.982518e-01  8.356851e-01   
301  3.096943  5.485607e-01  5.482845e-01  7.062777e-01  8.452837e-

In [4]:
DF_AGN          = pd.read_csv(data_dir+"logPkRatio_owls_AGN.dat"         ,sep='\s+')
DF_DBLIMFV1618  = pd.read_csv(data_dir+"logPkRatio_owls_DBLIMFV1618.dat" ,sep='\s+')
DF_NOSN         = pd.read_csv(data_dir+"logPkRatio_owls_NOSN.dat"        ,sep='\s+')
DF_NOSN_NOZCOOL = pd.read_csv(data_dir+"logPkRatio_owls_NOSN_NOZCOOL.dat",sep='\s+')
DF_NOZCOOL      = pd.read_csv(data_dir+"logPkRatio_owls_NOZCOOL.dat"     ,sep='\s+')
DF_REF          = pd.read_csv(data_dir+"logPkRatio_owls_REF.dat"         ,sep='\s+')
DF_WDENS        = pd.read_csv(data_dir+"logPkRatio_owls_WDENS.dat"       ,sep='\s+')
DF_WML1V848     = pd.read_csv(data_dir+"logPkRatio_owls_WML1V848.dat"    ,sep='\s+')
DF_WML4         = pd.read_csv(data_dir+"logPkRatio_owls_WML4.dat"        ,sep='\s+')
DF_ill1         = pd.read_csv(data_dir+"logPkRatio_ill1.dat"             ,sep='\s+')
DF_mb2          = pd.read_csv(data_dir+"logPkRatio_mb2.dat"              ,sep='\s+')
DF_eagle        = pd.read_csv(data_dir+"logPkRatio_eagle.dat"            ,sep='\s+')
DF_HzAGN        = pd.read_csv(data_dir+"logPkRatio_HzAGN.dat"            ,sep='\s+')

In [5]:
DF_AGN

logk          z350          z325          z300          z275  \
0   -3.301030 -1.315394e-23  0.000000e+00 -3.946183e-23 -1.315394e-23   
1   -3.191599  2.776356e-07  2.811956e-07  2.676021e-07  2.684451e-07   
2   -3.082169  2.381321e-07  2.411856e-07  2.295263e-07  2.302493e-07   
3   -2.972738 -1.185104e-07 -1.200300e-07 -1.142276e-07 -1.145874e-07   
4   -2.863308 -7.922919e-07 -8.024512e-07 -7.636594e-07 -7.660651e-07   
5   -2.753877 -8.148892e-07 -8.253383e-07 -7.854401e-07 -7.879144e-07   
6   -2.644446  1.362246e-06  1.379714e-06  1.313016e-06  1.317153e-06   
7   -2.535016  5.759355e-06  5.833206e-06  5.551219e-06  5.568706e-06   
8   -2.425585  1.237644e-05  1.253514e-05  1.192917e-05  1.196675e-05   
9   -2.316155  2.121349e-05  2.148551e-05  2.044686e-05  2.051127e-05   
10  -2.206724  3.227052e-05  3.268431e-05  3.110430e-05  3.120229e-05   
11  -2.097293  4.554752e-05  4.613156e-05  4.390149e-05  4.403979e-05   
12  -1.987863  6.104450e-05  6.182725e-05  5.883842e-05  5.902377e-05   
13  -1.878432  7.876145e-05  7.977138e-05  7.591510e-05  7.615424e-05   
14  -1.769002  9.869837e-05  9.996394e-05  9.513152e-05  9.543120e-05   
15  -1.659571  1.208553e-04  1.224049e-04  1.164877e-04  1.168546e-04   
16  -1.550141  1.452321e-04  1.470944e-04  1.399836e-04  1.404246e-04   
17  -1.440710  1.718290e-04  1.740323e-04  1.656193e-04  1.661410e-04   
18  -1.331279  2.006458e-04  2.032186e-04  1.933947e-04  1.940039e-04   
19  -1.221849  2.316826e-04  2.346534e-04  2.233098e-04  2.240133e-04   
20  -1.201820  2.376034e-04  2.406501e-04  2.290167e-04  2.297382e-04   
21  -0.900790  2.308661e-04  2.288917e-04  2.101008e-04  2.003477e-04   
22  -0.724699  2.173500e-04  2.055503e-04  1.715198e-04  1.401751e-04   
23  -0.599760  1.508418e-04  1.230604e-04  6.565702e-05  3.285204e-06   
24  -0.502850  9.484060e-05  4.902811e-05 -3.627784e-05 -1.377962e-04   
25  -0.423669  3.793454e-05 -2.902700e-05 -1.503682e-04 -3.074205e-04   
26  -0.356722 -8.471345e-05 -1.950705e-04 -3.721998e-04 -6.019793e-04   
27  -0.298730 -2.328016e-04 -3.800488e-04 -6.089053e-04 -9.097069e-04   
28  -0.247578 -3.693047e-04 -5.708747e-04 -8.758510e-04 -1.277188e-03   
29  -0.201820 -5.260266e-04 -7.852105e-04 -1.177122e-03 -1.696882e-03   
..        ...           ...           ...           ...           ...   
296  2.848191  1.946835e+00  1.938742e+00  1.902563e+00  1.930074e+00   
297  2.859498  1.970750e+00  1.962550e+00  1.926044e+00  1.954117e+00   
298  2.870805  1.994808e+00  1.986500e+00  1.949666e+00  1.978304e+00   
299  2.882112  2.019011e+00  2.010592e+00  1.973428e+00  2.002637e+00   
300  2.893419  2.043358e+00  2.034827e+00  1.997332e+00  2.027114e+00   
301  2.904725  2.067848e+00  2.059205e+00  2.021377e+00  2.051737e+00   
302  2.916032  2.092483e+00  2.083726e+00  2.045563e+00  2.076504e+00   
303  2.927339  2.117261e+00  2.108389e+00  2.069890e+00  2.101416e+00   
304  2.938646  2.142183e+00  2.133195e+00  2.094357e+00  2.126473e+00   
305  2.949953  2.167250e+00  2.158143e+00  2.118966e+00  2.151675e+00   
306  2.961260  2.192460e+00  2.183234e+00  2.143715e+00  2.177021e+00   
307  2.972567  2.217814e+00  2.208468e+00  2.168606e+00  2.202513e+00   
308  2.983874  2.243311e+00  2.233844e+00  2.193637e+00  2.228149e+00   
309  2.995181  2.268953e+00  2.259363e+00  2.218810e+00  2.253931e+00   
310  3.006488  2.294739e+00  2.285024e+00  2.244123e+00  2.279857e+00   
311  3.017795  2.320668e+00  2.310828e+00  2.269577e+00  2.305928e+00   
312  3.029101  2.346742e+00  2.336775e+00  2.295172e+00  2.332144e+00   
313  3.040408  2.372959e+00  2.362864e+00  2.320908e+00  2.358504e+00   
314  3.051715  2.399320e+00  2.389096e+00  2.346785e+00  2.385010e+00   
315  3.063022  2.425825e+00  2.415470e+00  2.372803e+00  2.411660e+00   
316  3.074329  2.452474e+00  2.441988e+00  2.398962e+00  2.438456e+00   
317  3.085636  2.479267e+00  2.468647e+00  2.425262e+00  2.465396e+00   
318  3.096943  2.506204e+00  2.495450e+00  2.451703e+00  2.492481e+

In [40]:
zmax=3.
zl=np.linspace(0,zmax,zmax/1.e-3)

/home/hungjinh/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: object of type <type 'float'> cannot be safely interpreted as an integer.
  


In [41]:
zl

array([  0.00000000e+00,   1.00033344e-03,   2.00066689e-03, ...,
         2.99799933e+00,   2.99899967e+00,   3.00000000e+00])

In [42]:
k=np.logspace(1.e-4,100,5000)

In [43]:
k

array([  1.00023029e+000,   1.04737929e+000,   1.09675080e+000, ...,
         9.11994120e+099,   9.54983832e+099,   1.00000000e+100])

In [11]:
PS=Power_Spectra()

In [24]:
PS.pk_params

{'kmax': 30, 'kmin': 0.0003, 'nk': 5000, 'non_linear': 1}

In [18]:
pk_params2=PS.pk_params.copy()
pk_params2['kmax']=1500

In [19]:
pk,k=PS.camb_pk(z=np.linspace(0,1,10),pk_params=pk_params2)

Note: redshifts have been re-sorted (earliest first)


In [20]:
pk.shape

(10, 5000)

In [22]:
k

array([  3.00000000e-04,   3.00927112e-04,   3.01857088e-04, ...,
         1.49077168e+03,   1.49537872e+03,   1.50000000e+03])

In [23]:
k.shape

(5000,)

In [ ]:
pk_ratio_intp=interp1d(k_ratio,pk_ratio,bounds_error=False,fill_value=1)
pk_ratio2=pk_ratio_intp(k)

In [ ]:

pk_bary=pk_ratio*pk

In [28]:
z=np.linspace(0,5,200)
pzs=lsst_zsource(z=z)
x=z<2
z=z[x]
pzs=pzs[x]

nbins=5
zs_bins=np.linspace(0.1,2,nbins+1) #source bins, tomography
lmax_cl=2000
lmin_cl=2
l=np.arange(lmin_cl,lmax_cl)
do_cov=False
bin_cl=False

In [29]:
kappaS = Kappa(zs=z,pzs=pzs,l=l,z_bins=zs_bins,do_cov=do_cov,bin_cl=bin_cl)

('changed kmax to', 8267.1812952697346, ' to cover rmin')
('j-nu=', 0, ' not enough zeros to cover kmin, increasing by ', 1000, ' to', 3000)
('j-nu=', 0, ' not enough zeros to cover kmin, increasing by ', 1000, ' to', 4000)
('pruning r, log_space,n_f:', True, 2)
('pruned r:', 73)
('nr:', 73)


In [36]:
clS=kappaS.kappa_cl_tomo(pk_func=PS.camb_pk,pk_params=pk_params2)

Note: redshifts have been re-sorted (earliest first)


In [33]:
zs_bins

array([ 0.1 ,  0.48,  0.86,  1.24,  1.62,  2.  ])

In [34]:
kappaS.zl

array([  1.00000000e-04,   1.10512539e-04,   1.22130212e-04,
         1.34969198e-04,   1.49157887e-04,   1.64838168e-04,
         1.82166844e-04,   2.01317204e-04,   2.22480753e-04,
         2.45869128e-04,   2.71716216e-04,   3.00280488e-04,
         3.31847591e-04,   3.66733197e-04,   4.05286167e-04,
         4.47892032e-04,   4.94976855e-04,   5.47011489e-04,
         6.04516283e-04,   6.68066292e-04,   7.38297019e-04,
         8.15910779e-04,   9.01683716e-04,   9.96473566e-04,
         1.10122824e-03,   1.21699528e-03,   1.34493238e-03,
         1.48631892e-03,   1.64256877e-03,   1.81524445e-03,
         2.00607272e-03,   2.21696189e-03,   2.45002087e-03,
         2.70758026e-03,   2.99221569e-03,   3.30677352e-03,
         3.65439937e-03,   4.03856952e-03,   4.46312570e-03,
         4.93231352e-03,   5.45082489e-03,   6.02384496e-03,
         6.65710400e-03,   7.35693463e-03,   8.13033523e-03,
         8.98503987e-03,   9.92959567e-03,   1.09734483e-02,
         1.21270363e-02,